name: CI
on:
  push:
  merge_group:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.3.0-rc0"
      - run: scarb fmt --check
      - run: scarb run test